### ISSUE TITLE
PlantUML Support not working

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/docker-pandoc#3]
This issue was originally created here cloudogu/docker-doc_template#1, but is actually caused by `docker-pandoc` (as it is the docker base image of `docker-doc_template`).

Generation of PlantUML in version 0.7.0 fails for this `test.md` (it works with 0.6.0!) :
```
~~~ {.plantuml }
@startuml
Bob -> Alice : hello
@enduml
~~~
```

The following error occurs:
```
! Unable to load picture or PDF file 'fc430039b32ed5ecaf6abf199ad73edc23d88f83.
png'.
<to be read again> 
                   }
l.168 ...0039b32ed5ecaf6abf199ad73edc23d88f83.png}
```
Even though the file `c430039b32ed5ecaf6abf199ad73edc23d88f83.png` is actually created. 

I found out that  `c430039b32ed5ecaf6abf199ad73edc23d88f83.png` actually is an SVG file (as realized in the [`cloudogu/docker-pandoc`](https://github.com/cloudogu/docker-pandoc/blob/50db8ce938ba2075470353a112f5afd41d755461/resources/plantuml) container) and changed `test.md` to:
```
~~~ {.plantuml format="svg"}
@startuml
Bob -> Alice : hello
@enduml
~~~
```
as described in [jodonoghue/pandoc-plantuml-filter](https://github.com/jodonoghue/pandoc-plantuml-filter/blob/7a7ddd614747e77f226be168cb3974c57ab6ec5d/src/HandlePlantUMLBlock.hs).

Now a, a `fc430039b32ed5ecaf6abf199ad73edc23d88f83.svg` is created but a different error occurs:
```
! LaTeX Error: Cannot determine size of graphic in fc430039b32ed5ecaf6abf199ad7
3edc23d88f83.svg (no BoundingBox).
```

**Comment by sdorra** [comment]
The PlantUML support is fixed in the version >= 0.8.0 and uses now eps graphics, which are looking much better than png.

The syntax is now ` ```uml ... ```  ` to fix conflicts with [smeagol](https://github.com/cloudogu/smeagol).
